export {
  OPENAI_IMAGE_SIZES,
  OPENAI_IMAGE_OUTPUT_FORMATS,
  OPENAI_IMAGE_RESPONSE_FORMATS,
  OPENAI_IMAGE_QUALITIES,
  OPENAI_VIDEO_DURATIONS,
  OPENAI_VIDEO_RATIOS,
  OPENAI_VIDEO_SIZES,
} from '@/lib/ai-providers/openai-compatible/models'
