export {
  VIDU_VIDEO_MODES,
  VIDU_STANDARD_RATIOS,
  VIDU_Q2_EXTRA_RATIOS,
  VIDU_AUDIO_TYPES,
  VIDU_MOVEMENT_AMPLITUDES,
  VIDU_RATIO_PATTERN,
  VIDU_MAX_PAYLOAD_LENGTH,
  type ViduModeSpec,
  type ViduSpec,
  VIDU_VIDEO_SPECS,
} from '@/lib/ai-providers/vidu/models'
