export const AI_PROMPT_IDS = {
  CHARACTER_ANALYZE: 'character-analyze',
  CHARACTER_VISUAL_PROFILE: 'character-visual-profile',
  CHARACTER_CREATE: 'character-create',
  CHARACTER_MODIFY: 'character-modify',
  CHARACTER_REGENERATE: 'character-regenerate',
  CHARACTER_UPDATE_DESCRIPTION: 'character-update-description',
  CHARACTER_REFERENCE_DESCRIBE_IMAGE: 'character-reference-describe-image',
  CHARACTER_REFERENCE_TO_SHEET: 'character-reference-to-sheet',
  LOCATION_ANALYZE: 'location-analyze',
  LOCATION_CREATE: 'location-create',
  LOCATION_MODIFY: 'location-modify',
  LOCATION_REGENERATE: 'location-regenerate',
  LOCATION_UPDATE_DESCRIPTION: 'location-update-description',
  PROP_ANALYZE: 'prop-analyze',
  PROP_UPDATE_DESCRIPTION: 'prop-update-description',
  SCRIPT_CLIP_SEGMENTS: 'script-clip-segments',
  SCRIPT_EPISODE_SPLIT: 'script-episode-split',
  SCRIPT_GENERATE_SCREENPLAY: 'script-generate-screenplay',
  SCRIPT_EXPAND_STORY: 'script-expand-story',
  STORYBOARD_PLAN: 'storyboard-plan',
  STORYBOARD_REFINE_CINEMATOGRAPHY: 'storyboard-refine-cinematography',
  STORYBOARD_REFINE_ACTING: 'storyboard-refine-acting',
  STORYBOARD_REFINE_DETAIL: 'storyboard-refine-detail',
  STORYBOARD_INSERT_PANEL: 'storyboard-insert-panel',
  STORYBOARD_EDIT: 'storyboard-edit',
  SHOT_VARIANT_ANALYZE: 'shot-variant-analyze',
  SHOT_VARIANT_GENERATE: 'shot-variant-generate',
  PANEL_IMAGE_GENERATE: 'panel-image-generate',
  IMAGE_UPDATE_SHOT_PROMPT: 'image-update-shot-prompt',
  DESIGN_VISUAL_STYLE_PRESET: 'design-visual-style-preset',
  DESIGN_DIRECTOR_STYLE_PRESET: 'design-director-style-preset',
  VOICE_GENERATE_LINES: 'voice-generate-lines',
  MUSIC_LYRIA_PROMPT_EXPAND: 'music-lyria-prompt-expand',
} as const

export type AiPromptId = (typeof AI_PROMPT_IDS)[keyof typeof AI_PROMPT_IDS]
