import { ARK_API_CONFIG_CATALOG_MODELS, ARK_BUILTIN_CAPABILITY_CATALOG_ENTRIES, ARK_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/ark/models'
import { BAILIAN_API_CONFIG_CATALOG_MODELS, BAILIAN_BUILTIN_CAPABILITY_CATALOG_ENTRIES, BAILIAN_BUILTIN_PRICING_CATALOG_ENTRIES, BAILIAN_DEFAULT_VOICE_DESIGN_MODEL_KEY } from '@/lib/ai-providers/bailian/models'
import { FAL_API_CONFIG_CATALOG_MODELS, FAL_BUILTIN_CAPABILITY_CATALOG_ENTRIES, FAL_BUILTIN_PRICING_CATALOG_ENTRIES, FAL_DEFAULT_LIPSYNC_MODEL_KEY, FAL_DEFAULT_VOICE_MODEL_KEY } from '@/lib/ai-providers/fal/models'
import { GOOGLE_API_CONFIG_CATALOG_MODELS, GOOGLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES, GOOGLE_BUILTIN_PRICING_CATALOG_ENTRIES, GOOGLE_COMPATIBLE_API_CONFIG_CATALOG_MODELS } from '@/lib/ai-providers/google/models'
import { MINIMAX_API_CONFIG_CATALOG_MODELS, MINIMAX_BUILTIN_CAPABILITY_CATALOG_ENTRIES, MINIMAX_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/minimax/models'
import { OPENAI_COMPATIBLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES, OPENAI_COMPATIBLE_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/openai-compatible/models'
import { OPENROUTER_API_CONFIG_CATALOG_MODELS, OPENROUTER_BUILTIN_CAPABILITY_CATALOG_ENTRIES, OPENROUTER_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/openrouter/models'
import { SILICONFLOW_BUILTIN_CAPABILITY_CATALOG_ENTRIES, SILICONFLOW_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/siliconflow/models'
import { VIDU_API_CONFIG_CATALOG_MODELS, VIDU_BUILTIN_CAPABILITY_CATALOG_ENTRIES, VIDU_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/vidu/models'

export const BUILTIN_CAPABILITY_CATALOG_ENTRIES = [
  ...ARK_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...BAILIAN_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...FAL_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...GOOGLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...MINIMAX_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...OPENAI_COMPATIBLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...OPENROUTER_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...SILICONFLOW_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...VIDU_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
] as const

export const BUILTIN_PRICING_CATALOG_ENTRIES = [
  ...ARK_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...BAILIAN_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...FAL_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...GOOGLE_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...MINIMAX_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...OPENAI_COMPATIBLE_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...OPENROUTER_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...SILICONFLOW_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...VIDU_BUILTIN_PRICING_CATALOG_ENTRIES,
] as const

export const BUILTIN_API_CONFIG_CATALOG_MODELS = [
  ...ARK_API_CONFIG_CATALOG_MODELS,
  ...BAILIAN_API_CONFIG_CATALOG_MODELS,
  ...FAL_API_CONFIG_CATALOG_MODELS,
  ...GOOGLE_API_CONFIG_CATALOG_MODELS,
  ...MINIMAX_API_CONFIG_CATALOG_MODELS,
  ...OPENROUTER_API_CONFIG_CATALOG_MODELS,
  ...VIDU_API_CONFIG_CATALOG_MODELS,
] as const

export const BUILTIN_DEFAULT_LIPSYNC_MODEL_KEY = FAL_DEFAULT_LIPSYNC_MODEL_KEY
export const BUILTIN_DEFAULT_VOICE_MODEL_KEY = FAL_DEFAULT_VOICE_MODEL_KEY
export const BUILTIN_DEFAULT_VOICE_DESIGN_MODEL_KEY = BAILIAN_DEFAULT_VOICE_DESIGN_MODEL_KEY

export const BUILTIN_GOOGLE_COMPATIBLE_API_CONFIG_CATALOG_MODELS = [
  ...GOOGLE_COMPATIBLE_API_CONFIG_CATALOG_MODELS,
] as const
